### ISSUE TITLE
Demo failed to work

### ISSUE THREAD

**Issue by blamot** [viniciusalmeida/ninja-presentation#14]
The demo doesn't work, this is my console output:

'HTMLHeadElement.profile' is deprecated. The reflected attribute has no effect.

'HTMLVideoElement.webkitDisplayingFullscreen' is deprecated. Please use the 
'fullscreenchange' and 'webkitfullscreenchange' events instead.

'HTMLVideoElement.webkitSupportsFullscreen' is deprecated. Its value is true if the video is loaded.

2Uncaught RangeError: Maximum call stack size exceeded deprecated.js:12

Uncaught SecurityError: Blocked a frame with origin "https://www.youtube.com" from accessing a frame with origin "http://viniciusalmeida.github.io".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

**Comment by trevordmiller** [comment]
@viniciusalmeida: This is a great idea...but I am getting the same errors as @blamot:
![screen shot 2014-08-01 at 10 27 39 pm](https://cloud.githubusercontent.com/assets/5497885/3787091/5d1c7438-19fd-11e4-852e-20dec4e7e128.png)
Will you please fix these issues so that we can use your web component? Thank you.

**Comment by viniciusalmeida** [comment]
Fixed on PR https://github.com/viniciusalmeida/ninja-presentation/issues/15
